### PR TITLE
added openpgp encryption/decryption 

### PR DESCRIPTION
**Pull request by yykcool**
problems with trying to get tests working, currently commented out pending further fixes.

### CODE REVIEW

**Comment by john-dot-oa** [comment]
Expo QR
Published to https://exp.host/@workpasssg/sg-workpass?release-channel=storybook-5

**Comment by john-dot-oa** [comment]
Expo QR
Published to https://exp.host/@workpasssg/sg-workpass?release-channel=5

**Comment by john-dot-oa** [comment]
Expo QR
Published to https://exp.host/@workpasssg/sg-workpass?release-channel=storybook-5

**Comment by john-dot-oa** [comment]
Expo QR
Published to https://exp.host/@workpasssg/sg-workpass?release-channel=5

**Comment by john-dot-oa** [comment]
Expo QR
Published to https://exp.host/@workpasssg/sg-workpass?release-channel=storybook-5

**Comment by john-dot-oa** [comment]
Expo QR
Published to https://exp.host/@workpasssg/sg-workpass?release-channel=5

**Comment by yehjxraymond** [comment]
Pls ignore the messages, was setting up pipeline elsewhere and forgot to change some config

**Pull request merged**
